name: 'Fetch Secret JS'
description: 'JavaScript version of the action to fetch secrets from a vault'
inputs:
  base_url:
    description: 'The base URL of the vault API'
    required: true
  auth_type:
    description: 'Authentication type (token, userpass)'
    required: false
    default: 'token'
  api_token:
    description: 'The API token for token-based authentication'
    required: false
  username:
    description: 'Username for userpass authentication'
    required: false
  password:
    description: 'Password for userpass authentication'
    required: false
  vault_uid:
    description: 'Vault UID for login'
    required: false
  secrets:
    description: 'Multi-line string mapping output type, box name, and secret name to environment variable or file path'
    required: true
outputs:
  secret:
    description: 'The fetched secret'
runs:
  using: 'node20'
  main: 'dist/index.js'
