name: 'secrets-vault-action'
description: 'GitHub Action to fetch secrets from a Entrust Keycontrol Secret Vault'
inputs:
  base_url:
    description: 'The base URL of the vault API'
    required: true
  auth_type:
    description: 'Authentication type (token, userpass)'
    required: false
    default: 'token'
  api_token:
    description: 'The API token for token-based authentication'
    required: false
  username:
    description: 'Username for userpass authentication'
    required: false
  password:
    description: 'Password for userpass authentication'
    required: false
  tls_verify_skip: 
    description: 'Skip TLS verification (true/false)'
    required: false
    default: false
  ca_cert:
    description: 'Base64 encoded CA certificate'
    required: false
  vault_uid:
    description: 'Vault UID for login, required for userpass authentication'
    required: false
  secrets:
    description: 'Multi-line string mapping box name, and secret name to environment variable'
    required: true
outputs:
  secret:
    description: 'The fetched secret'
runs:
  using: 'node20'
  main: 'dist/index.js'
