name: Test Secrets Vault Action Token Auth

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
      - master
    paths:
      - '.github/workflows/auth_type-token.yml'

jobs:
  test-vault-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Fetch secret from Secrets vault
        id: fetch-secret
        uses: EntrustCorporation/secrets-vault-action@v1
        with:
          base_url: ${{ secrets.BASE_URL }}
          api_token: ${{ secrets.API_TOKEN }}
          ca_cert: ${{ secrets.CA_CERT }}
          secrets: |
            Box1.DOCKER_USERNAME | DOCKER_USERNAME;
            Box1.DOCKER_PASSWORD | DOCKER_PASSWORD;

      - name: Verify secret was retrieved
        if: steps.fetch-secret.outcome == 'success'
        run: |
          echo "Secret was successfully retrieved"

      - name: Display the secret (for testing only)
        if: steps.fetch-secret.outcome == 'success'
        run: |
          # Display the actual secret for testing purposes

          echo "Retrieved DOCKER_USERNAME: ${{ steps.fetch-secret.outputs.DOCKER_USERNAME }}"

          echo "Retrieved DOCKER_USERNAME: ${DOCKER_USERNAME}"
